import {
  Center,
  Container,
  Heading,
  Tab,
  TabList,
  TabPanel,
  TabPanels,
  Tabs,
} from "@chakra-ui/react";
import Head from "next/head";
import CardRapat from "../components/landing/CardRapat";
import Hero from "../components/landing/Hero";
import Footer from "../components/layout/Footer";
// import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container
        maxW={"5xl"}
        minHeight="90vh"
        // bg={useColorModeValue("gray.100", "gray.800")}
      >
        <Hero />
        <Center p={10}>
          <Heading size="lg">List Jadwal Rapat</Heading>
        </Center>
        <Tabs colorScheme="red">
          <TabList>
            <Tab>Yang akan datang 📋</Tab>
            <Tab>Semua rapat ✔</Tab>
          </TabList>

          <TabPanels>
            <TabPanel>
              <CardRapat />
              <CardRapat />
              <CardRapat />
            </TabPanel>

            <TabPanel>
              <CardRapat />
              <CardRapat />
              <CardRapat />
            </TabPanel>
          </TabPanels>
        </Tabs>
      </Container>
      <Container maxW={"5xl"}>
        <Footer />
      </Container>
    </>
  );
}
